FROM php:8.4-cli

# Установка необходимых расширений PHP
RUN docker-php-ext-install pdo_mysql

# Установка Composer
RUN curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer

WORKDIR /var/www/html
